---
output:
  html_document:
        theme: null
        highlight: null
        mathjax: null
---
**Base Points**: Locations which are intended and expected to be sampled, although the actual implementation of the design may result in some base points being rejected or unsampleable (see: oversample points). The total number of base points represents the sample size for the design and each base point is associated with a panel.

**Oversample Points**: Extra sample points which are selected at the time of the sample draw. These points are used to supplement the base points when a base point is rejected or not sampled. A design should have enough oversample points to replace all rejected/unsampleable base points in order to reach the intended sample size. Oversample points should only be sampled once all base points in a design have been sampled or rejected.

**Panel**: A set of sample points that have the same revisit pattern across years. For example, a design might be divided into 5 panels, each representing a different year. All points within a single panel visited in 2017, would then be visited in 2022, 2027, and so on. The points visited 2017 through 2022 together make up the entire sample design. It is also acceptable to use only one panel for a multiple year design and use the year of first sampling to establish the revisit pattern, *e.g.* if a point was sampled in the second of five years, it now belongs to panel 2 and will be revisited every five years counting from that year.

**Population**: The entire “universe” to which the results of sampling apply. The population is defined by many factors; the area you’re interested in, objectives, and other constraints. The population includes *all* and *only* locations that may possibly be sampled; any areas that would not be sampled are not part of the population.

**Sample Design**: Provides information on the intended and actual sample sizes, strata definitions, and the sample selection methodology. This term is often used interchangeable with “sample plan”, “survey design”, “sampling plan” or “sampling design”.

**Sample Frame**: A representation of the target population. The sample frame is the geographic extent of the population and therefore covers *all* and *only* the areas which may possibly be sampled.

**Sample Point/Reach/Plot**: Location where data have been or are intended to be collected. For terrestrial sampling, this is most often called a plot. For aquatic sampling, this is typically a stream reach. In some documents, the phrase "sample point" is used to refer to both.

**Sample Size**: The number of points or plots in the that need to be sampled within a stratum to analyze data to ensure a desired level of precision and accuracy. The sample size can influence the types of analyses you can perform and the uncertainty of the results. The sample size across the study area is a function of several factors:

  1) Existing or legacy monitoring information, *e.g.* Having existing and usable data may mean that less new data needs to be collected.
  2) Statistical considerations, *e.g.* What analyses will be needed? What are the desired confidence level and confidence interval?
  3) Funding and personnel limitations, *e.g.* How many points per year can actually be sampled by data collectors?

**Sampling**: Using selected members to estimate attributes of a larger population. This takes the form of visiting a location and collecting data/observations for that location.

**Sampled Population**: The portion of the target population that is actually sampled. Due to real-world constraints on implementation of a sample design, this usually does not perfectly match the target population.

**Seed Number**: A number used as the basis for random numbers by a piece of software. A random outcome will be the same every single time as long as the same seed number is used. This allows for random sample designs that are also reproducible.

**Spatially Balanced Sampling**: An approach in which sampling is evenly spaced across study area. This is dependent on the implementation of the sample design following correct sampling order to maximize spatial dispersion of any sequence of sample points.

*NOTE*: The spatial balance of a sample design is only preserved if the points are sampled in ascending numerical order within strata and maintaining sampling proportions between sample, *e.g.* if stratum 1 has 20 points and stratum 2 has 40 points, by the time half of stratum 1 points are sampled (the first 10 points of stratum 1), half of stratum 2 should also be sampled (the first 20 points of stratum 2).

**Stratification**: Stratification refers to dividing a population or study area into subgroups or subunits called strata for the purposes of sampling or data analysis. Reasons to stratify include:

  1) Variability and range of indicators is dependent on spatial factors, *e.g.* different ecosystem types (often represented with Ecological Sites, LANDFIRE Biophysical Settings, or Strahler stream order) will have different potentials and may be grouped into strata.
  2) Ensure different types of land (especially types with small spatial extents) are sampled, *e.g.* if Sage-Grouse habitat is important to the intended use of a design but makes up a very small portion, it may be its own stratum in order to guarantee that some points are drawn for it.