---
output:
  html_document:
        theme: null
        highlight: null
        mathjax: null
---
Polygon shapefiles are complex things and unfortunately this tool can't identify and repair all of the possible sources of problems that will cause it to fail.

Almost all crashes due to shapefile geometry (that the tool's repair option does not correct) can be solved one of two ways:

**1) Dissolving**: Dissolving the polygons by the stratification field is easy and works in almost every case. If there are other attributes of the polygons that you want to preserve but will be lost in the dissolve (*e.g.* multiple polygons belong to the same stratum but it is important to capture that they belong to different administrative units), be sure to retain those polygons with the full information and create a new, separate shapefile from the dissolve process.

**2) Buffering**: Buffering the polygons by a distance of 0 units can also solve crashes. This will cause no user-noticeable changes to the polygons or their attributes, but does generally force tiny changes to the underlying geometry that correct common issues like slivers or discontinuities. Note that not all geoprocessing software will allow for buffering with a distance of 0.

If you are encountering repeated crashing with a shapefile, even with the option to check and repair geometry selected, chances are that there are some irregularities or errors in the geometry that crept in during the geoprocessing that created the polygons. These are almost always due to quirks of the geoprocessing software rather than mistakes on a user's part. Many geometry errors may not be readily apparent, especially if you use Arc software like ArcGIS which does an excellent job of glossing over and working around most geometry errors, making them invisible to users. Another cause can be memory allocation issues for particularly complicated polygons. This seems to happen most often when there are dozens to thousands of entries per stratum in the polygon attributes instead of a single entry for each. However, some sets of polygons may be complex enough that this tool will be unable to handle them.

For further help or to report bugs, please email [Nelson Stauffer](mailto:nelson.stauffer@usda.gov).