# This is a basic workflow to help you get started with Actions

name: Pushing changes to Dockerhub and updating service

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: landscapedatacommons/balanced-design-tool:4.2.1
#      - uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SERVER_IP }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          password: ${{ secrets.SERVER_PASSWORD }}
#          script: |
#            docker service update shinyproxy-toolbox_balanced-design-tool \
#            --image=docker.io/landscapedatacommons/balanced-design-tool:4.2.1
